### ISSUE TITLE
android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file

### ISSUE THREAD

**Issue by i906** [epsilonlabsllc/DataManagement#1] opened 2013-04-13 03:47 UTC
The problem randomly occurs to a small number of my app users. I am unable to reproduce it though.

There are instances where the database is open/closed multiple times.

Stack trace:

```
android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file
at android.database.sqlite.SQLiteDatabase.dbopen(Native Method)
at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:983)
at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:956)
at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1021)
at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:778)
at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:221)
at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:149)
at net.epsilonlabs.datamanagementefficient.library.PersistenceManager.open(SourceFile:52)
at net.epsilonlabs.datamanagementefficient.library.DataManager.open(SourceFile:58)
...
at java.lang.Thread.run(Thread.java:1020)
```

I am using data-management-1.0.3-02262013.jar.

**Comment by skeswa** [comment] 2013-04-13 03:49
Thanks for the heads up i906. We're checking it out as soon as possible.

**Comment by tcaputi** [comment] 2013-04-13 03:56
Are all users who experience this issue using ICS and up?

**Comment by i906** [comment] 2013-04-13 03:59
It seems to happen on Android 3.2 only.

**Comment by tcaputi** [comment] 2013-04-13 04:08
Would it be possible for you to send us the code that is causing this issue? I can assure you we will not release this code and it will only be used for debugging purposes. You can send it to contactus@epsilonlabsllc.com

**Comment by tcaputi** [comment] 2013-04-13 04:29
Also check that you always close the DataManager before you open it again. Under normal circumstances, this should not cause an issue at least according to android's documentation, but there may be a bug specific to Android 3.2. The SQLite method that DataManager.open() calls which is failing is SQLHelper.getWritableDatabase(), which is implemented by Android. According to the documentation of that method:

"Once opened successfully, the database is cached, so you can call this method every time you need to write to the database. (Make sure to call close() when you no longer need the database.) Errors such as bad permissions or a full disk may cause this method to fail, but future attempts may succeed if the problem is fixed."

If you can, please try to ensure that none of these are happening.

**Comment by i906** [comment] 2013-04-13 04:35
The code that is used is quite big, but here is a sample code that runs similarly.

```
import java.util.ArrayList;

import net.epsilonlabs.datamanagementefficient.exception.DatabaseNotOpenExpection;
import net.epsilonlabs.datamanagementefficient.library.DataManager;
import android.content.Context;

public class TestLib {

    private static final Object LOCK = new Object();
    private static DataManager database;
    private static boolean initialized;

    public static void init(final Context context) {        
        if (initialized) return;        
        database = DataManager.getInstance(context);
        initialized = true;
    }

    /**
     * 
     * This function is always called from other classes, sometimes is called
     * multiple times concurrently.
     * 
     */
    public static void refreshData(final Context context) {

        // This is always called.
        String closest_code = getClosestCode();

        // This might be called sometimes depending on the inputs.
        String some_new_code = "x";
        saveLocationCache(some_new_code);
    }

    /**
     * The crashes seemed to point here.
     */
    private static String getClosestCode() {
        String code = null;

        synchronized (LOCK) {
            database.open();
            ArrayList<LocationCache> rcdb = database.getAll(LocationCache.class);

            for (LocationCache lc : rcdb) {
                // Some process here
                code = lc.code;
            }

            try {
                database.close();
            } catch (DatabaseNotOpenExpection e) { }
        }

        return code;
    }

    /**
     * This function is called less frequently.
     */
    private static void saveLocationCache(String code) {
        LocationCache lc = new LocationCache();
        lc.code = code;

        synchronized (LOCK) {
            database.open();
            database.add(lc);
            database.close();
        }       
    }

}
```

**Comment by tcaputi** [comment] 2013-04-13 04:37
Thank you, I will look at this now.

**Comment by tcaputi** [comment] 2013-04-13 05:14
I only have 1 suggestion as far as your code is concerned. The "try... catch (DatabaseNotOpenExpection e)" block you have implies that somewhere in the code block you abbreviated as "// Some process here" there may be more open() and close() calls to the database. If this is so, I suggest you make sure that the database is never opened while it is already open. Although this should not cause any issues, there may be an Android 3.2 implementation bug that is out of my control to fix. If not, I will continue to research this issue and find an answer if I can. I apologize for the inconvenience to you and your users.

**Comment by tcaputi** [comment] 2013-04-18 20:52
We are adding internal concurrency support to DataMangement, which should be available (hopefully) within a few days. This may solve your issue, but until then this issue has been marked as irreplicable and closed.

**Closed as completed by tcaputi** 2013-04-18 20:52 UTC
